### ISSUE TITLE
[dglo on 2015-05-14 12:21:24] : pDAQ: eventBuilder - include string-position info in error message

### ISSUE THREAD

**Issue by dglo** [dglo/payload#177]
Event builder errors would be much more useful if they included the string number in this error message:

Caused by: icecube.daq.payload.PayloadException: Couldn't find hit record for TemporaryHit[114893910712249903 dom 1c2cd3e2e645] (chanId 3523)
	at icecube.daq.payload.impl.TriggerRecord.computeIndices(EventPayload_v5.java:324)
	at icecube.daq.payload.impl.EventPayload_v5.putTriggerRecords(EventPayload_v5.java:1090)

**Comment by dglo** [comment]
[dglo on 2015-08-24 16:00:20]
svn commit -m"Issue 7368: The DOM registry should be a class-wide static attribute, not added to every object"
Sending        eventBuilder-prod/src/main/java/icecube/daq/eventBuilder/backend/EventBuilderBackEnd.java
Sending        payload/src/main/java/icecube/daq/payload/IEventFactory.java
Sending        payload/src/main/java/icecube/daq/payload/impl/EventFactory.java
Sending        payload/src/main/java/icecube/daq/payload/impl/EventPayload_v5.java
Transmitting file data ....done
Committing transaction...
Committed revision 15698.

svn commit -m"Issue 7368: Add more DOM description info to make problems easier to diagnose" payload/src/main/java/icecube/daq/payload/impl/EventPayload_v5.java
Sending        payload/src/main/java/icecube/daq/payload/impl/EventPayload_v5.java
Transmitting file data .done
Committing transaction...
Committed revision 15699.

**Comment by dglo** [comment]
[dglo on 2016-03-22 11:05:54]
New_Glarus is almost here!
