### ISSUE TITLE
[dglo on 2007-06-13 12:13:28] : payload - UTCTime8B.compareTo() can get a NullPointerException

### ISSUE THREAD

**Issue by dglo** [dglo/payload#23]
Run 108656 seems to have died due to this exception:

Exception in thread "HKN1Splicer" java.lang.NullPointerException
    at icecube.daq.payload.impl.UTCTime8B.compareTo(UTCTime8B.java:139)
    at icecube.daq.trigger.algorithm.SimpleMajorityTrigger.runTrigger(SimpleMajorityTrigger.
java:218) 
    at icecube.daq.trigger.control.TriggerHandler.process(TriggerHandler.java:291)
    at icecube.daq.trigger.control.TriggerManager.execute(TriggerManager.java:173)
    at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:332)
    at java.lang.Thread.run(Thread.java:799)

**Comment by dglo** [comment]
[dglo on 2007-06-13 13:33:25]
-- Clean up default constructor and getOffsetUTCTime(), fix bugs in compareTo()
Sending        src/main/java/icecube/daq/payload/impl/UTCTime8B.java
Committed revision 1612.
-- Add UTCTime8B unit tests
Adding         src/test/java/icecube/daq/payload/impl/UTCTime8BTest.java
Committed revision 1613.

**Comment by dglo** [comment]
[master 460c0fe] 1 changed, 1 inserted, 1 deleted

**Comment by dglo** [comment]
[master 85db2d9] 1 changed, 1 inserted, 0 deleted
